service: diagram-generator-api

provider:
  name: aws
  iam:
    role: arn:aws:iam::150209693186:role/LabRole
  runtime: python3.9
  region: us-east-1 # Puedes cambiar la región si lo deseas
  stage: dev
  environment:
    TABLE_NAME: ${self:service}-${sls:stage}-diagrams

functions:
  generateFlowchart:
    handler: src/functions/generate_flowchart.generate_flowchart
    events:
      - http:
          path: diagrams/flowchart
          method: post
          cors: true
  generateERD:
    handler: src/functions/generate_erd.generate_erd
    events:
      - http:
          path: diagrams/erd
          method: post
          cors: true
  generateJSONSchema:
    handler: src/functions/generate_json_schema.generate_json_schema
    events:
      - http:
          path: diagrams/json-schema
          method: post
          cors: true

resources:
  Resources:
    DiagramsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-diagrams
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-python-requirements
  - serverless-offline # Para desarrollo local